name: CI

on:
  push:
    branches: [main]
    paths-ignore: ["**/*.md", "LICENSE", ".gitignore"]
  pull_request:
    branches: [main]
    paths-ignore: ["**/*.md", "LICENSE", ".gitignore"]
  workflow_dispatch:

jobs:
  ci:
    uses: cplieger/ci/.github/workflows/shell-ci.yaml@e43ece37b63835a7531016d100b5e2912e420541 # v1
