name: CI

on:
  push:
    branches: [main]
    paths-ignore: ["**/*.md", "LICENSE", ".gitignore"]
  pull_request:
    branches: [main]
    paths-ignore: ["**/*.md", "LICENSE", ".gitignore"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: cplieger/ci/.github/workflows/shell-ci.yaml@4e0a6937409828785a87d9eba577315d6cce50e0 # v1
