name: Security

on:
  pull_request:
    paths:
      - "Dockerfile"
      - ".github/workflows/security.yml"
  schedule:
    - cron: "17 5 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    uses: cplieger/ci/.github/workflows/security-scan.yaml@bbb84133e2512f24cf9e89fc67d43d378d299360 # v1
    with:
      scan-type: "both"
